:project:
  :name: xbee_project
  :test_file_prefix: test_
  :build_root: build    
  :source:
    - src
  :test:
    - test

:paths:
  :source:
    - src
  :include:
    - include     
    - src         
  :test:
    - test
  :mockable:
    - include

:plugins:
  :enabled:
    - stdout_pretty_tests_report

:cmock:
  :mock_prefix: mock_
  :treat_inlines: :include
  :when_no_prototypes: :warn
  :plugins:
    - expect
    - ignore
    - expect_any_args
  :mock_path: build/test/mocks