:project:
  :name: xbee_project
  :test_file_prefix: test_
  :build_root: build    
  :source:
    - src
  :test:
    - test

:paths:
  :source:
    - src
  :include:
    - include     
    - src         
  :test:
    - test

:plugins:
  :enabled:
    - report_tests_pretty_stdout