name: Doxygen Pages

on:
  push:            # run on every push (all branches)
    branches: ["**"]
  pull_request:    # optional – still produces the artifact

permissions:
  contents: read
  pages: write     # allow the deploy-pages action to publish
  id-token: write  # required by deploy-pages

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen + Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate docs
        run: doxygen Doxyfile            # OUTPUT_DIRECTORY = docs

      # 1️⃣  Upload the generated site as a Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/html                # <— exact folder with index.html

  # 2️⃣  Deploy the artifact to GitHub Pages
  deploy:
    needs: docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2