# .github/workflows/doxygen.yml
name: Doxygen Docs

# ➊ Build docs for every push (any branch) and on each PR
on:
  push:
    branches: [ "**" ]      # match *all* branch names
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------------------
      - name: Checkout source
        uses: actions/checkout@v4

      # ------------------------------------------------------------------
      # ➋ Create a file-system-safe slug from the ref name
      #    (slashes → dashes, everything else unchanged)
      # ------------------------------------------------------------------
      - name: Prepare ref slug
        id: slug
        run: |
          echo "SLUG=${GITHUB_REF_NAME//\//-}" >> "$GITHUB_OUTPUT"

      # ------------------------------------------------------------------
      # Install Doxygen + Graphviz
      # ------------------------------------------------------------------
      - name: Install Doxygen & Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      # ------------------------------------------------------------------
      # Generate documentation
      # Assumes your Doxyfile writes HTML to docs/html
      # ------------------------------------------------------------------
      - name: Generate docs
        run: doxygen Doxyfile

      # ------------------------------------------------------------------
      # ➌ Upload HTML as a run artifact (handy for PR review)
      # ------------------------------------------------------------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # e.g. doxygen-feature-xbee-cellular-3
          name: doxygen-${{ steps.slug.outputs.SLUG }}
          path: docs/html

      # ------------------------------------------------------------------
      # ➍ Deploy every branch to GitHub Pages under its own folder
      #     gh-pages/<branch-or-tag-slug>/
      # ------------------------------------------------------------------
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/html
          # Folder on gh-pages: one per branch, with slashes removed
          destination_dir: ${{ steps.slug.outputs.SLUG }}