# .github/workflows/doxygen.yml
name: Doxygen Docs

# ────────────────────────────────
# Run on every push + every PR
# ────────────────────────────────
on:
  push:
    branches: ["**"]          # all branches
  pull_request:               # PRs from forks included

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    # ────────────────────────────────
    # 1. Checkout code
    # ────────────────────────────────
    - uses: actions/checkout@v4

    # ────────────────────────────────
    # 2. Install Doxygen tool-chain
    # ────────────────────────────────
    - name: Install Doxygen & Graphviz
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    # ────────────────────────────────
    # 3. Build docs    (OUTPUT_DIRECTORY = docs )
    # ────────────────────────────────
    - name: Generate documentation
      run: doxygen Doxyfile

    # ────────────────────────────────
    # 4. Upload artifact (easy download
    #    from PR overview)
    # ────────────────────────────────
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs-${{ github.ref_name }}
        path: docs/html
        retention-days: 7

    # ────────────────────────────────
    # 5. Publish to gh-pages
    #
    #    • one sub-folder per branch
    #        main   ➜ /
    #        develop➜ /develop/
    #        feat/x ➜ /feat-x/
    #
    # ────────────────────────────────
    - name: Deploy to gh-pages
      if: github.event_name == 'push'       # don’t deploy from PRs
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages            # branch will be created automatically
        publish_dir: docs/html
        destination_dir: |
          ${{ github.ref_name == 'main' && '' || github.ref_name }}